version: 2.1

workflows:
  develop:
    jobs:
      - build:
          context: app
jobs:
  build:
    docker:
      - image: circleci/golang:1.14
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    working_directory: ~/repo
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - go-mod-v4-{{ checksum "go.sum" }}
      - run:
          name: Install Dependencies
          command: go get ./...
      - save_cache:
          key: go-mod-v4-{{ checksum "go.sum" }}
          paths:
            - "/go/pkg/mod"
      - run:
          name: Test
          command: make test
      - run:
          name: Build
          command: make build
      - run:
          name: Docker Release
          command: |
            make docker
      - store_artifacts:
          path: ~/repo/out
